FROM openjdk:8-jre-slim
ENV CLUSTER_NAME=FOXPASS
COPY . /opt
WORKDIR /opt
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - 
RUN apt-get update && apt-get install -y nodejs
ENV NODE_VERSION=16.13.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version
#CMD ["./run_docker_helix_ui_server.sh"]
